=== pluxain/clantl/public/schemas/checklist.schema.json
{
  "$id": "https://raw.githubusercontent.com/pluxain/clantl/refs/heads/main/public/schemas/checklist.schema.json",
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "CheckList",
  "description": "JSON Schema for a CheckList in clantl",
  "type": "object",
  "properties": {
    "items": {
      "description": "KillerItems of the CheckList",
      "type": "array",
      "items": {
        "description": "KillerItem of a CheckList",
        "$ref": "https://raw.githubusercontent.com/pluxain/clantl/refs/heads/main/public/schemas/killeritem.schema.json"
      },
      "minItems": 1,
      "maxItems": 8,
      "uniqueItems": true
    },
    "kind": {
      "description": "The discriminating property of the file",
      "const": "CheckList"
    },
    "locale": {
      "description": "Locale of the CheckList",
      "enum": ["en", "fr"]
    },
    "name": {
      "description": "Name of the CheckList",
      "type": "string"
    },
    "nextStep": {
      "description": "Next Step after the CheckList is completed",
      "type": "string"
    },
    "realm": {
      "description": "Which Realm belongs the CheckList",
      "type": "string"
    },
    "step": {
      "description": "Which Step belongs the CheckList",
      "type": "string"
    }
  },
  "required": ["items", "locale", "name", "nextStep", "realm", "step"]
}

=== pluxain/clantl/public/data/anesthesie/start/001.json
{
  "$schema": "https://raw.githubusercontent.com/pluxain/clantl/refs/heads/main/public/schemas/checklist.schema.json",
  "items": [
    {
      "label": "patient",
      "keyword": "nommé",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "nature de l'intervention",
      "keyword": "nommée",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "zone de l'intervention",
      "keyword": "définie",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "examen préanesthésique",
      "keyword": "effectué",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "consentement du propriétaire",
      "keyword": "signé",
      "kind": "KillerItem",
      "verified": false
    }
  ],
  "kind": "CheckList",
  "locale": "fr",
  "name": "avant prémédication",
  "nextStep": "preparation-et-premedication",
  "realm": "anesthesie",
  "step": "start"
}

=== pluxain/clantl/public/data/anesthesie/start/checklist.json
{
  "$schema": "https://clantl.lechainonmanquant.studio/schemas/checklist.schema.json",
  "items": [
    {
      "label": "patient",
      "keyword": "nommé",
      "verified": false
    },
    {
      "label": "nature de l'intervention",
      "keyword": "nommée",
      "verified": false
    },
    {
      "label": "zone de l'intervention",
      "keyword": "définie",
      "verified": false
    },
    {
      "label": "examen préanesthésique",
      "keyword": "effectué",
      "verified": false
    },
    {
      "label": "consentement du propriétaire",
      "keyword": "signé",
      "verified": false
    }
  ],
  "locale": "fr",
  "name": "avant prémédication",
  "nextStep": "preparation-et-premedication",
  "realm": "anesthesie",
  "step": "start"
}

=== pluxain/clantl/public/data/anesthesie/preparation-et-premedication/checklist.json
{
  "$schema": "https://raw.githubusercontent.com/pluxain/clantl/refs/heads/main/public/schemas/checklist.schema.json",
  "items": [
    {
      "label": "matériel d'intubation",
      "keyword": "vérifié",
      "verified": false
    },
    {
      "label": "oxygène",
      "keyword": "disponible",
      "verified": false
    },
    {
      "label": "circuit / Ballon de réanimation",
      "keyword": "testé",
      "verified": false
    },
    {
      "label": "valve d'échappement",
      "keyword": "Ouverte",
      "verified": false
    },
    {
      "label": "ballonnet sonde endotrachéale",
      "keyword": "étanche",
      "verified": false
    },
    {
      "label": "cathéter",
      "keyword": "fonctionnel",
      "verified": false
    },
    {
      "label": "procédure de réanimation",
      "keyword": "prête",
      "verified": false
    },
    {
      "label": "responsable de la surveillance",
      "keyword": "nommé",
      "verified": false
    }
  ],
  "locale": "fr",
  "name": "avant induction",
  "nextStep": "induction",
  "realm": "anesthesie",
  "step": "preparation-et-premedication"
}

=== pluxain/clantl/public/data/anesthesie/induction/checklist.json
{
  "$schema": "https://raw.githubusercontent.com/pluxain/clantl/refs/heads/main/public/schemas/checklist.schema.json",
  "items": [
    {
      "label": "parient / intervention / zone",
      "keyword": "confirmés",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "adjuvant analgésique",
      "keyword": "en place",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "profondeur de l'anesthésie",
      "keyword": "vérifiée",
      "kind": "KillerItem",
      "verified": false
    }
  ],
  "kind": "CheckList",
  "locale": "fr",
  "name": "avant chirurgie",
  "nextStep": "chirurgie",
  "realm": "anesthesie",
  "step": "induction"
}

=== pluxain/clantl/public/data/anesthesie/chirurgie/001.json
{
  "$schema": "https://raw.githubusercontent.com/pluxain/clantl/refs/heads/main/public/schemas/checklist.schema.json",
  "items": [
    {
      "label": "plan thérapeutique post-intervention",
      "keyword": "défini",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "plan analgésique",
      "keyword": "en place",
      "kind": "KillerItem",
      "verified": false
    },
    {
      "label": "surveillance post-anesthésique",
      "keyword": "définie",
      "kind": "KillerItem",
      "verified": false
    }
  ],
  "kind": "CheckList",
  "locale": "fr",
  "name": "avant réveil",
  "nextStep": "reveil",
  "realm": "anesthesie",
  "step": "chirurgie"
}
